# spring.application.name=studio
# server.port=${PORT:8082}

# spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
# spring.datasource.username=postgres.dladqguqoagquvlsawat
# spring.datasource.password=Aniket%root
# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.mvc.view.prefix=/WEB-INF/views/
# spring.mvc.view.suffix=.jsp
# spring.servlet.multipart.enabled=true
# spring.servlet.multipart.max-file-size=400MB
# spring.servlet.multipart.max-request-size=400MB
spring.application.name=studio
server.port=${PORT:8082}

spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.dladqguqoagquvlsawat
spring.datasource.password=Aniket%root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=400MB
spring.servlet.multipart.max-request-size=400MB
